import { test, expect } from '@playwright/test';
import path from 'path';
import fs from 'fs';

const globalVarsPath = path.join(__dirname,  '../../global-variables.json');
let globalVariables = JSON.parse(fs.readFileSync(globalVarsPath, 'utf8'));

test('Registered Accused Join Case Test', async ({ page }) => {
test.setTimeout(180000);
  console.log('Navigating to Citizen login page...');
  await page.goto(`${globalVariables.baseURL}ui/citizen/select-language`);
  await page.getByRole('button').click();
  await page.getByRole('textbox').click();
  console.log('Filling accused litigant mobile number...');
  await page.getByRole('textbox').fill(globalVariables.accusedLitigant);
  await page.waitForTimeout(1000);
  await page.getByRole('button').click();
  console.log('Filling OTP...');
  await page.locator('.input-otp').first().fill('1');
  await page.locator('input:nth-child(2)').fill('2');
  await page.locator('input:nth-child(3)').fill('3');
  await page.locator('input:nth-child(4)').fill('4');
  await page.locator('input:nth-child(5)').fill('5');
  await page.locator('input:nth-child(6)').fill('6');
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.waitForTimeout(1000);
  console.log('Joining case...');
  await page.getByRole('button', { name: 'Join Case' }).click();
  console.log('Filling case number...');
  await page.locator('input[name="caseNumber"]').click();
  await page.waitForTimeout(1000);
  await page.locator('input[name="caseNumber"]').fill(globalVariables.filingNumber);
  await page.waitForTimeout(1000);
  console.log('Searching case...');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.waitForTimeout(1000);
  await page.locator('.cp').first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.waitForTimeout(1000);
  console.log('Filling validation code...');
  await page.locator('input[name="validationCode"]').click();
  await page.locator('input[name="validationCode"]').click();
  await page.waitForTimeout(1000);
  await page.locator('input[name="validationCode"]').fill(globalVariables.accessCode);
  await page.waitForTimeout(1000);
  console.log('Verifying validation code...');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.waitForTimeout(2000);
  console.log('Finalizing join case...');
  await page.getByRole('button', { name: 'Join Case' }).nth(1).click();
  await page.waitForTimeout(2000);
  console.log('Selecting accused role...');
  await page.locator('div').filter({ hasText: /^Accused$/ }).getByRole('radio').check();
  console.log('Selecting not representing anyone...');
  await page.locator('div').filter({ hasText: /^No$/ }).getByRole('radio').check();
  console.log('Selecting accused...');
  await page.locator('div').filter({ hasText: /^Which litigant are you\?$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Which litigant are you\? Automation Accused$/ }).getByRole('img').click();
  await page.locator('div').filter({ hasText: /^Which litigant are you\?$/ }).getByRole('img').click();
  await page.locator('#jk-dropdown-unique div').click();
  console.log('Confirming joining as party in person...');
  await page.locator('div').filter({ hasText: /^Are you joining as a Party in Person\?YesNo$/ }).locator('span').nth(2).click();
  console.log('Proceeding to join case...');
  await page.getByRole('button', { name: 'Proceed' }).click();
  console.log('Accused joined the case successfully.');
  await page.waitForTimeout(5000);
  await page.waitForLoadState('networkidle');
  
});

