import { test, expect } from '@playwright/test';
import path from 'path';
import fs from 'fs';

const globalVarsPath = path.join(__dirname,  '../../global-variables.json');
let globalVariables = JSON.parse(fs.readFileSync(globalVarsPath, 'utf8'));

test('Accused Advocate joining the case as replacing the Pip by taking judge approval with payment', async ({ page }) => {
test.setTimeout(180000);
  console.log('Navigating to Citizen login page...');
  await page.goto(`${globalVariables.baseURL}ui/citizen/select-language`);
  await page.getByRole('button').click();
  await page.getByRole('textbox').click();
  console.log('Filling advocate mobile number...');
  await page.getByRole('textbox').fill(globalVariables.accusedADV);
  await page.waitForTimeout(1000);
  await page.getByRole('button').click();
  console.log('Filling OTP...');
  await page.locator('.input-otp').first().fill('1');
  await page.locator('input:nth-child(2)').fill('2');
  await page.locator('input:nth-child(3)').fill('3');
  await page.locator('input:nth-child(4)').fill('4');
  await page.locator('input:nth-child(5)').fill('5');
  await page.locator('input:nth-child(6)').fill('6');
  await page.waitForTimeout(1000);
  console.log('Verifying OTP...');
  await page.getByRole('button', { name: 'Verify' }).click();
  console.log('Joining case...');
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Join Case' }).click();
  console.log('Filling case number...');
  await page.locator('input[name="caseNumber"]').click();
  await page.waitForTimeout(1000);
  await page.locator('input[name="caseNumber"]').fill(globalVariables.filingNumber);
  await page.waitForTimeout(1000);
  console.log('Searching case...');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.waitForTimeout(1000);
  console.log('Selecting case from search results...');
  await page.locator('.cp').first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.waitForTimeout(1000);
  console.log('Filling validation code...');
  await page.locator('input[name="validationCode"]').click();
  await page.locator('input[name="validationCode"]').click();
  await page.waitForTimeout(1000);
  await page.locator('input[name="validationCode"]').fill(globalVariables.accessCode);
  await page.waitForTimeout(1000);
  console.log('Verifying validation code...');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.waitForTimeout(2000);
  console.log('Finalizing join case...');
  await page.getByRole('button', { name: 'Join Case' }).nth(1).click();
  await page.waitForTimeout(2000);
  console.log('Selecting advocate role...');
  await page.locator('div').filter({ hasText: /^Accused$/ }).getByRole('radio').check();
  console.log('Selecting representing someone...');
  await page.locator('div').filter({ hasText: /^Yes$/ }).getByRole('radio').check();
  console.log('Selecting accused litigant which need to be represented ...');
  await page.locator('div').filter({ hasText: /^Which litigant\(s\) are you representing\?$/ }).getByRole('textbox').click();
  console.log('Selecting the litigant from the dropdown...');
  await page.locator('div').filter({ hasText: /^Automation Accused$/ }).getByRole('checkbox').check();
//   await page.getByRole('heading', { name: 'Are you representing a' }).click();
  await page.getByText('BackProceed').click();
  console.log('Replacing existing party in person...');
  await page.locator('div').filter({ hasText: /^Which advocates are you replacing\?$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Select All$/ }).getByRole('checkbox').check();
//   await page.getByText('Are you replacing an existing Advocate/Party in PersonYesNo').click();
  await page.getByText('BackProceed').click();
  console.log('Selecting judge as an approval role...');
  await page.locator('div').filter({ hasText: /^Judge$/ }).getByRole('radio').check();
  await page.getByRole('textbox', { name: 'Type here' }).click();
  await page.getByRole('textbox', { name: 'Type here' }).fill('replacement text');
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.locator('input[name="noOfAdvocates"]').click();
  await page.locator('input[name="noOfAdvocates"]').fill(globalVariables.noOfAdvocates);
  await page.waitForTimeout(1000);
  await page.locator('input[type="file"]').setInputFiles("./Test.png");
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.waitForTimeout(5000);
  await page.waitForLoadState('networkidle');
  
});

