// Dedicated single-flow for Others application, to run in headed mode easily
test.describe('@submission Others single', () => {
  test('Create Others application and reach submission success', async ({ page }) => {
    await loginCitizen(page);

    const home = new HomePage(page);
    await home.goto();
    await expect(home.table).toBeVisible();

    // Filter by Stage=Cognizance and open latest case by Case ID
    await home.openCognizanceLatestCase();

    const submission = new SubmissionPage(page);

    // Select application type: Others
    await submission.selectApplicationType('Others');

    // Fill reason/prayer and add supporting doc
    await submission.fillReason('Others application generated by automated E2E test.');
    await submission.fillPrayer('Kindly approve this application in the interest of justice.');
    await submission.setDocType('Affidavits');
    await submission.setDocTitle('Others - supporting affidavit');
    await submission.uploadSupportingDoc(SUPPORT_DOC);

    // Generate, review, sign by upload
    await submission.generateApplication();
    await submission.addSignatureByUpload(SIGNED_DOC);
    await submission.expectSigned();

    // Proceed and handle payment section (skip when offline)
    await submission.proceedAfterSignature();
    await submission.skipPayment();

    // Expect success banner
    await submission.expectSuccessPanel();
    const id = await submission.getSubmissionId();
    console.log('Submission ID (Others single):', id);
  });
});