/**
 * csv.js — CSV-based test data loader (replaces excel.js)
 * ─────────────────────────────────────────────────────────────────────────────
 * Pure Node.js, zero external dependencies.
 *
 * Reads one row from data/test-data.csv and writes it to the correct
 * environment JSON file (e.g. data/global-variablesdemo.json) so that the
 * existing loadGlobalVariables() / saveGlobalVariables() helpers continue to
 * work without any change inside the spec files.
 *
 * CSV layout (generated by helpers/generate-csv.js):
 *   Row 1  → column headers  (flowLabel, baseURL, citizenUsername, …)
 *   Row 2  → Flow 1 test data
 *   Row 3  → Flow 2 test data
 *   …
 *   Row 8  → Flow 7 test data
 *
 * Usage (called from run-all-flows.js):
 *   const { loadRowFromCsv } = require('../../helpers/csv');
 *   loadRowFromCsv({ rowIndex: 0, env: 'demo' });   // 0-based data row
 *
 * After this call, data/global-variablesdemo.json is refreshed with that
 * row's values and the next Playwright test run will pick them up.
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── Paths ──────────────────────────────────────────────────────────────────

const DATA_DIR = path.join(__dirname, '..', 'data');
const CSV_FILE = path.join(DATA_DIR, 'test-data.csv');

// These columns control the runner — not written to the globals JSON
const SKIP_COLUMNS = new Set(['flowLabel', 'specFile']);

// ─── RFC-4180 CSV Parser ─────────────────────────────────────────────────────

/**
 * Parse a CSV string into an array of row-objects.
 * Handles:
 *   - Quoted fields (fields enclosed in double-quotes)
 *   - Embedded commas inside quotes
 *   - Embedded newlines inside quotes (multi-line fields)
 *   - Escaped double-quotes inside quoted fields ("")
 *
 * @param {string} text  Raw CSV content
 * @returns {object[]}   Array of {header: value} objects (header row auto-mapped)
 */
function parseCsv(text) {
    // Normalise line endings
    const src = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    const rows = [];
    let row = [];
    let field = '';
    let inQuotes = false;
    let i = 0;

    const flush = () => { row.push(field); field = ''; };

    while (i < src.length) {
        const ch = src[i];
        const next = src[i + 1];

        if (inQuotes) {
            if (ch === '"' && next === '"') {
                // Escaped quote inside quoted field
                field += '"';
                i += 2;
            } else if (ch === '"') {
                // End of quoted field
                inQuotes = false;
                i++;
            } else {
                field += ch;
                i++;
            }
        } else {
            if (ch === '"') {
                inQuotes = true;
                i++;
            } else if (ch === ',') {
                flush();
                i++;
            } else if (ch === '\n') {
                flush();
                rows.push(row);
                row = [];
                i++;
            } else {
                field += ch;
                i++;
            }
        }
    }

    // Flush last field / row
    if (field || row.length > 0) {
        flush();
        rows.push(row);
    }

    // Remove trailing empty rows (trailing newline artefacts)
    while (rows.length && rows[rows.length - 1].every((f) => f === '')) {
        rows.pop();
    }

    if (rows.length < 2) return [];

    const headers = rows[0];
    return rows.slice(1).map((cells) => {
        const obj = {};
        headers.forEach((h, idx) => {
            obj[h] = cells[idx] ?? '';
        });
        return obj;
    });
}

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Returns the absolute path of the environment JSON file.
 * Mirrors the logic in env.js.
 *
 * @param {string} env  e.g. 'demo', 'qa', 'uat', '' (default)
 * @returns {string}
 */
function jsonPathForEnv(env) {
    const name = (env || '').trim().toLowerCase();
    return name
        ? path.join(DATA_DIR, `global-variables${name}.json`)
        : path.join(DATA_DIR, 'global-variables.json');
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Reads one data row from data/test-data.csv and writes it to the
 * environment-specific JSON file (e.g. data/global-variablesdemo.json).
 *
 * The JSON is fully replaced so stale keys from a previous flow don't leak.
 * Dynamic keys (filingNumber, cmpNumber, etc.) will be re-populated by
 * saveGlobalVariables() as the flow progresses.
 *
 * @param {object} options
 * @param {number} options.rowIndex  0-based index into data rows (excluding header).
 *                                   Row 0 → Flow 1, Row 1 → Flow 2, …
 * @param {string} [options.env]     Environment name. Defaults to TEST_ENV.
 * @returns {object}                 The globals object written to disk.
 */
function loadRowFromCsv({ rowIndex, env } = {}) {
    const envName = (env || process.env.TEST_ENV || '').trim().toLowerCase();
    const outPath = jsonPathForEnv(envName);

    if (!fs.existsSync(CSV_FILE)) {
        throw new Error(
            `[csv.js] CSV file not found: ${CSV_FILE}\n` +
            `  Run: node helpers/generate-csv.js --env=${envName || 'demo'}\n` +
            `  to create it from the existing global-variables JSON.`
        );
    }

    const text = fs.readFileSync(CSV_FILE, 'utf8');
    const rows = parseCsv(text);

    if (rows.length === 0) {
        throw new Error(`[csv.js] No data rows found in ${CSV_FILE}.`);
    }

    if (rowIndex < 0 || rowIndex >= rows.length) {
        throw new Error(
            `[csv.js] rowIndex ${rowIndex} is out of range. ` +
            `CSV has ${rows.length} data row(s) (0 – ${rows.length - 1}).`
        );
    }

    const raw = rows[rowIndex];

    // Build globals — skip informational columns
    const globals = {};
    for (const [key, value] of Object.entries(raw)) {
        if (SKIP_COLUMNS.has(key)) continue;
        globals[key] = (value ?? '').toString().trim();
    }

    // Write to disk
    fs.mkdirSync(DATA_DIR, { recursive: true });
    fs.writeFileSync(outPath, JSON.stringify(globals, null, 2), 'utf8');

    console.log(
        `[csv.js] ✅  Row ${rowIndex + 1} → ${path.relative(process.cwd(), outPath)} ` +
        `(${Object.keys(globals).length} keys)`
    );

    return globals;
}

/**
 * Returns all data rows from the CSV as objects (without writing to disk).
 * @returns {object[]}
 */
function getAllRowsFromCsv() {
    if (!fs.existsSync(CSV_FILE)) {
        throw new Error(`[csv.js] CSV file not found: ${CSV_FILE}`);
    }
    return parseCsv(fs.readFileSync(CSV_FILE, 'utf8'));
}

module.exports = { loadRowFromCsv, getAllRowsFromCsv, jsonPathForEnv };
