/**
 * excel.js — Excel-based test data loader
 * ─────────────────────────────────────────────────────────────────────────────
 * Reads one row from data/test-data.xlsx (generated by helpers/generate-excel.js)
 * and writes it to the correct environment JSON file so that the existing
 * loadGlobalVariables() / saveGlobalVariables() helpers in env.js continue
 * to work without any change in the spec files.
 *
 * Sheet layout (TestData):
 *   Column A  → flowLabel  (human-readable, ignored by this loader)
 *   Column B… → all keys from global-variables<env>.json
 *
 *   Row 1     → headers
 *   Row 2     → Flow 1 data
 *   Row 3     → Flow 2 data
 *   …
 *   Row 8     → Flow 7 data
 *
 * How run-all-flows.js uses this:
 *   Before running each spec file it calls:
 *     loadRowFromExcel({ rowIndex: <0-based>, env: 'demo' });
 *   This overwrites data/global-variablesdemo.json with that row's values,
 *   so the next Playwright process reads fresh test data from the Excel.
 *
 * Usage from run-all-flows.js:
 *   const { loadRowFromExcel } = require('../../helpers/excel');
 *   loadRowFromExcel({ rowIndex: 0, env: 'demo' });   // Flow 1
 *   loadRowFromExcel({ rowIndex: 1, env: 'demo' });   // Flow 2
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

// ─── Paths ──────────────────────────────────────────────────────────────────

const DATA_DIR = path.join(__dirname, '..', 'data');
const EXCEL_FILE = path.join(DATA_DIR, 'test-data.xlsx');
const SHEET_NAME = 'TestData';

// Column that is informational-only (not written to JSON)
const SKIP_COLUMNS = new Set(['flowLabel']);

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Returns the absolute path of the environment JSON file.
 * Mirrors the logic in env.js so they always agree on the file name.
 *
 * @param {string} env  e.g. 'demo', 'qa', 'uat', '' (default)
 * @returns {string}
 */
function jsonPathForEnv(env) {
    const name = (env || '').trim().toLowerCase();
    return name
        ? path.join(DATA_DIR, `global-variables${name}.json`)
        : path.join(DATA_DIR, 'global-variables.json');
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Reads one data row from data/test-data.xlsx and writes it to the
 * environment-specific JSON file (e.g. data/global-variablesdemo.json).
 *
 * The JSON is fully replaced so that stale keys from a previous run don't
 * leak into the next flow. Dynamic keys (filingNumber, cmpNumber, etc.)
 * will be repopulated by saveGlobalVariables() as the flow progresses.
 *
 * @param {object} options
 * @param {number} options.rowIndex  0-based index into data rows (not the header).
 *                                  Row 0 → Flow 1, Row 1 → Flow 2, …
 * @param {string} [options.env]    Environment name ('demo', 'qa', …).
 *                                  Defaults to process.env.TEST_ENV.
 * @returns {object}                The globals object written to disk.
 */
function loadRowFromExcel({ rowIndex, env } = {}) {
    const envName = (env || process.env.TEST_ENV || '').trim().toLowerCase();
    const outPath = jsonPathForEnv(envName);

    if (!fs.existsSync(EXCEL_FILE)) {
        throw new Error(
            `[excel.js] Excel file not found: ${EXCEL_FILE}\n` +
            `  Run: node helpers/generate-excel.js --env=${envName || 'demo'}\n` +
            `  to create it from the existing global-variables JSON.`
        );
    }

    // Read sheet as array-of-objects (header row is auto-mapped to keys)
    const wb = XLSX.readFile(EXCEL_FILE);
    const ws = wb.Sheets[SHEET_NAME];

    if (!ws) {
        throw new Error(
            `[excel.js] Sheet "${SHEET_NAME}" not found in ${EXCEL_FILE}.\n` +
            `  Available: ${wb.SheetNames.join(', ')}`
        );
    }

    const rows = XLSX.utils.sheet_to_json(ws, { defval: '' });

    if (rows.length === 0) {
        throw new Error(`[excel.js] No data rows found in sheet "${SHEET_NAME}".`);
    }

    if (rowIndex < 0 || rowIndex >= rows.length) {
        throw new Error(
            `[excel.js] rowIndex ${rowIndex} is out of range. ` +
            `Sheet has ${rows.length} data row(s) (0 – ${rows.length - 1}).`
        );
    }

    const raw = rows[rowIndex];

    // Build the globals object — skip informational-only columns
    const globals = {};
    for (const [key, value] of Object.entries(raw)) {
        if (SKIP_COLUMNS.has(key)) continue;

        if (value === null || value === undefined || value === '') {
            globals[key] = '';
        } else if (typeof value === 'number') {
            // Phone numbers / IDs stored as numbers in Excel → keep as string
            globals[key] = String(value);
        } else {
            globals[key] = typeof value === 'string' ? value.trim() : value;
        }
    }

    // Write to disk
    fs.mkdirSync(DATA_DIR, { recursive: true });
    fs.writeFileSync(outPath, JSON.stringify(globals, null, 2), 'utf8');

    console.log(
        `[excel.js] ✅  Row ${rowIndex + 1} → ${path.relative(process.cwd(), outPath)} ` +
        `(${Object.keys(globals).length} keys)`
    );

    return globals;
}

/**
 * Returns all data rows from the Excel as objects, without writing to disk.
 * Useful for inspection / debugging.
 *
 * @returns {object[]}
 */
function getAllRowsFromExcel() {
    if (!fs.existsSync(EXCEL_FILE)) {
        throw new Error(`[excel.js] Excel file not found: ${EXCEL_FILE}`);
    }
    const wb = XLSX.readFile(EXCEL_FILE);
    const ws = wb.Sheets[SHEET_NAME];
    return XLSX.utils.sheet_to_json(ws, { defval: '' });
}

module.exports = { loadRowFromExcel, getAllRowsFromExcel, jsonPathForEnv };
